import { Element, AspectType } from "@astro-app/shared-types";
import type { ChartTheme } from "./types.js";

export const darkTheme: ChartTheme = {
  name: "dark",
  background: "#0A0E17",
  ringStroke: "#2A3040",
  ringStrokeWidth: 1,
  signDividerStroke: "#2A3040",
  signDividerWidth: 1,
  elementColors: {
    [Element.Fire]: "#E85D4A",
    [Element.Earth]: "#5BA858",
    [Element.Air]: "#5B9FD4",
    [Element.Water]: "#7B6DB5",
  },
  elementBgOpacity: 0.08,
  planetGlyph: "#E8ECF1",
  planetGlyphRetrograde: "#F87171",
  houseStroke: "#2A3040",
  houseStrokeWidth: 1,
  angleStroke: "#6C8EEF",
  angleStrokeWidth: 2,
  houseNumberColor: "#565E6C",
  aspectColors: {
    [AspectType.Conjunction]: "#E8ECF1",
    [AspectType.SemiSextile]: "#565E6C",
    [AspectType.Sextile]: "#5B9FD4",
    [AspectType.Square]: "#E85D4A",
    [AspectType.Trine]: "#5BA858",
    [AspectType.Quincunx]: "#FBBF24",
    [AspectType.Opposition]: "#E85D4A",
    [AspectType.SemiSquare]: "#565E6C",
    [AspectType.Sesquisquare]: "#565E6C",
    [AspectType.Quintile]: "#565E6C",
    [AspectType.BiQuintile]: "#565E6C",
  },
  aspectMajorWidth: 1.5,
  aspectMinorWidth: 1,
  aspectMinorDash: [4, 4],
  degreeLabelColor: "#8892A4",
  leaderLineColor: "#2A3040",
  fontFamily: "Inter, system-ui, -apple-system, sans-serif",
  signGlyphColor: "#8892A4",
};
