import { Element, AspectType } from "@astro-app/shared-types";
import type { ChartTheme } from "./types.js";

export const lightTheme: ChartTheme = {
  name: "light",
  background: "#FFFFFF",
  ringStroke: "#D0D5DD",
  ringStrokeWidth: 1,
  signDividerStroke: "#D0D5DD",
  signDividerWidth: 1,
  elementColors: {
    [Element.Fire]: "#E85D4A",
    [Element.Earth]: "#5BA858",
    [Element.Air]: "#5B9FD4",
    [Element.Water]: "#7B6DB5",
  },
  elementBgOpacity: 0.18,
  planetGlyph: "#1A1D24",
  planetGlyphRetrograde: "#DC2626",
  houseStroke: "#D0D5DD",
  houseStrokeWidth: 1,
  angleStroke: "#4A6FD4",
  angleStrokeWidth: 2,
  houseNumberColor: "#8892A4",
  aspectColors: {
    [AspectType.Conjunction]: "#1A1D24",
    [AspectType.SemiSextile]: "#8892A4",
    [AspectType.Sextile]: "#4A8BC2",
    [AspectType.Square]: "#D4533F",
    [AspectType.Trine]: "#3A60D0",
    [AspectType.Quincunx]: "#D97706",
    [AspectType.Opposition]: "#D4533F",
    [AspectType.SemiSquare]: "#8892A4",
    [AspectType.Sesquisquare]: "#8892A4",
    [AspectType.Quintile]: "#8892A4",
    [AspectType.BiQuintile]: "#8892A4",
  },
  aspectMajorWidth: 1.5,
  aspectMinorWidth: 1,
  aspectMinorDash: [4, 4],
  degreeLabelColor: "#5A6275",
  leaderLineColor: "#D0D5DD",
  fontFamily: "Inter, system-ui, -apple-system, sans-serif",
  signGlyphColor: "#5A6275",
};
